CREATE TABLE [dbo].[Exceptions]
(
	[Id] BIGINT IDENTITY PRIMARY KEY,
	[SourceGuid] UNIQUEIDENTIFIER NOT NULL,
	[ExString] NVARCHAR(MAX),
	[InsertDate] DATETIME2 NOT NULL DEFAULT(SYSDATETIME())
	INDEX IX_SourceGuid (SourceGuid)
)
