CREATE TABLE [dbo].[KeyGuid] (
    [Id]         UNIQUEIDENTIFIER NOT NULL,
    [Key]        VARCHAR (64)     NOT NULL,
    [InsertDate] DATETIME         DEFAULT (getdate()) NOT NULL,
    PRIMARY KEY NONCLUSTERED HASH ([Id]) WITH (BUCKET_COUNT = 131072),
    UNIQUE NONCLUSTERED ([Key] ASC)
)
WITH (MEMORY_OPTIMIZED = ON);

