CREATE TABLE [dbo].[RuggerName] (
    [Id]   UNIQUEIDENTIFIER NOT NULL,
    [Name] NVARCHAR (50)    NULL,
    [Bio] NVARCHAR (MAX)    NULL,
    [CreateDate] DATETIME2 NOT NULL DEFAULT SYSDATETIME()
    PRIMARY KEY CLUSTERED ([Id] ASC) WITH (DATA_COMPRESSION = PAGE)
);

